### ISSUE TITLE
Live Examples for Main Variants

### ISSUE THREAD

**Issue by julmot** [FrDH/mmenu-light#9]
I think it would be worth providing a live example on the plugin's homepage to see e.g. both off canvas / normal variants in action. It's very hard for me currently to get everything up and running. Pasting the [tutorial code](https://mmenujs.com/mmenu-light/tutorial.html) into jsfiddle also doesn't seem to generate a proper example: [Fiddle](https://jsfiddle.net/z3oy0hbf/1/)

**Comment by FrDH** [comment]
Thanks for the suggestion.
The menu, without off-canvas behaviro, has no `height` (it can not guess what height you need it to be). You therefor need to add some CSS, for example:
````css
#my-menu {
  height: 400px;
}
````
Or, if it's abolutely positioned:
````css
#my-menu {
  top: 0;
  bottom: 0;
}
````

Hope this helps.
